### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by technige** [technige/escli#1]
- [ ] Create project structure
- [ ] Add `version` command
- [ ] Add basic `search` command to match all
- [ ] Add license, readme, etc
- [ ] Upload first pre-release
- [ ] Allow configurable host and port
- [ ] Extend search capabilities
- [ ] Add `index` command
- [ ] Add `update` command
- [ ] Add `delete` command
